# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, '4.0' ]
  pull_request:
    branches: [ master, '4.0' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      # Runs a single command using the runners shell
      - name: Build
        run: |
          psql -c 'CREATE DATABASE pomm_test' -U postgres -h 127.0.0.1 postgres
          psql -c 'CREATE EXTENSION hstore' -U postgres -h 127.0.0.1 pomm_test
          psql -c 'CREATE EXTENSION ltree' -U postgres  -h 127.0.0.1 pomm_test
          composer install --dev
          cp sources/tests/config.github.php sources/tests/config.php

      - name: PHPStan Static Analysis
        uses: php-actions/phpstan@v2
        with:
          configuration: phpstan.neon
          memory_limit: 256M
          path: ''
          php_version: 8.4

      # Runs a set of commands using the runners shell
      - name: Run tests
        run: |
          php vendor/atoum/atoum/bin/atoum --version
          php vendor/atoum/atoum/bin/atoum --no-code-coverage -d sources/tests/Unit/